version: '3'

services:
  web:

    build: .

    container_name: world-of-games-container

    ports:
      - "8777:5000"

    environment:
      - FLASK_APP=MainScores.py

    command: flask run --host=0.0.0.0

    volumes:
      - .:/app
      - ./dummy_scores.txt:/app/Scores.txt
